[package]
name = "ffmml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
textparse = "0.0.2"

[workspace]
members = ["ffmml2wav"] # ffmml_cli(?)

[patch.crates-io]
textparse = { path = "../textparse/" }
